### ISSUE TITLE
Feature request: Debris cleanup

### ISSUE THREAD

**Issue by kontu** [N1Ran/GridSplitNameKeeper#1]
We discussed this on Discord, I figured it'd be good to actually submit it here for tracking:

Hey I had a thought for a plugin that would....fit really well with what gridsplitnamekeeper already does...
Essentially combat confetti sucks. We were thinking it'd be handy if on grid split event we could just grid.close() anything under X blocks; where X would likely be 5 or less.
Not sure what kind of perf hit that would take to add in a grid.close() to the split events during combat though; but it seemed proper to ask you since it's already triggering something on that event anyways 
 We figure it would make a huge help with confetti combat lag; and we didn't want to reinvent the wheel and have two separate things tracking grid splits
If you add it somewhere; would you mind making the size threshold configurable too? Never matters to me if it's gui or just the cfg

**Comment by N1Ran** [comment]
Ha!  Totally forgot 🖕

**Comment by N1Ran** [comment]
Added to v1.1.2
