### ISSUE TITLE
Auto naming for subgrids

### ISSUE THREAD

**Issue by BartekSz95** [N1Ran/GridSplitNameKeeper#2]
I have idea for new thing for GridSplitNameKeeper. It is auto naming for clang subgrids like piston, rotor, etc. This will be very useful, because players on my server change name for subgrids manually.

**Comment by N1Ran** [comment]
Doing this will force player's grid's subgrids to always take the name of the main grid...and can cause player's named grid to take default name if the code sees the subgrid as the main grid (happens sometimes)
