### ISSUE TITLE
[Feature Request] - Configurable list of blocks to cause a split to be ignored from deletion

### ISSUE THREAD

**Issue by kontu** [N1Ran/GridSplitNameKeeper#3]
We primarily use the gridsplit cleanup option for the huge benefit it provides in combat and crash situations to sim; but were wondering if you'd be willing to add the ability to list "restricted blocks" basically that it skips over - kind of like you did hardcode wise with cockpits, but let us set up the list. It'd be fine if it used only subtype and not pairname or type or anything if that's more performant; but we'd find it handy to be able to prevent cargo's or refineries (and similar) from being removed on some of our servers but not all

**Comment by N1Ran** [comment]
do you want it to skip over the block itself or the split that contains the block.  Be more specific

**Comment by kontu** [comment]
Sorry, re-reading it I can see it's unclear

If split contains (restricted block); do not clean up split at all

**Comment by N1Ran** [comment]
done
