### ISSUE TITLE
Delete feature does not sync correctly with clients

### ISSUE THREAD

**Issue by Blaylock1988** [N1Ran/GridSplitNameKeeper#5]
When a block splits and gets deleted by the plugin, it doesn't sync to the client so the block stays floating in space and obstructing other things until the client re-logs.

This seems to be a new problem, post Warfare2 update.

**Comment by N1Ran** [comment]
it wasn't the warfare update that caused it.  It was the new code that removed the Thread.Sleep which used to delay the code to prevent desyncs.  Current code is for better perf at the cost of desync.  Will add a network code to force sync with clients, but it will increase outgoing data on the server when this happens.

**Comment by Blaylock1988** [comment]
For now I have to disable the cleanup feature entirely since for us the desync problems FAR outweigh any performance benefits. Splits happen more often than you realize until you see blocks are floating all over the place. We have dozens of players complaining daily about un-grindable floating blocks obstructing vision and placement.

**Comment by N1Ran** [comment]
fixed
